import img from "../../assets/logo.jpg";

const data = [
	{
		id: 1,
		category: "Journal Papers",
		image: img,
		title: "Nazari, S., Eftekhari, A. M., & Moin, M. S. (2013).",
		desc: "Secure information transmission using steganography and morphological associative memory. International Journal of Computer Applications, 61(7).",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:Tyk-4Ss8FVUC",
		github: "https://civilica.com",
	},
	{
		id: 2,
		category: "Journal Papers",
		image: img,
		title: "Nazari, S., & Moin, M. S. (2013).",
		desc: "Cover selection steganography via run length matrix and human visual system.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:qjMakFHDy7sC",
		github: "https://civilica.com",
	},
	{
		id: 3,
		category: "Journal Papers",
		image: img,
		title: "Nazari, S., Eftekhari-Moghadam, A. M., & Moin, M. S. (2015).",
		desc: "A novel image steganography scheme based on morphological associative memory and permutation schema. Security and Communication Networks, 8(2), 110-121.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:IjCSPb-OGe4C",
		github: "https://civilica.com",
	},
	{
		id: 4,
		category: "Journal Papers",
		image: img,
		title: "Nazari, S., Moin, M. S., & Kanan, H. R. (2016).",
		desc: "A face template protection approach using chaos and GRP permutation. Security and Communication Networks, 9(18), 4957-4972.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:W7OEmFMy1HYC",
		github: "https://civilica.com",
	},
	{
		id: 5,
		category: "Journal Papers",
		image: img,
		title: "Nazari, S., Moin, M. S., & Kanan, H. R. (2018).",
		desc: "Securing templates in a face recognition system using error-correcting output code and chaos theory. Computers & Electrical Engineering, 72, 644-659.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:2osOgNQ5qMEC",
		github: "https://civilica.com",
	},
	{
		id: 6,
		category: "Journal Papers",
		image: img,
		title: "Nazari, S., Moin, M. S., & Kanan, H. R. (2019).",
		desc: "A discriminant binarization transform using genetic algorithm and error-correcting output code for face template protection. International Journal of Machine Learning and Cybernetics, 10, 433-449.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:zYLM7Y9cAGgC",
		github: "https://civilica.com",
	},
	{
		id: 7,
		category: "Journal Papers",
		image: img,
		title: "Aghabeigi, F., Nazari, S., & Osati Iraqi, N. (2022).",
		desc: "Deep Learning: Concepts, Types, Applications, and Implementation. Theory of Approximation and Applications, 14(1).",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:roLk4NBRz8UC",
		github: "https://civilica.com",
	},
	{
		id: 8,
		category: "Journal Papers",
		image: img,
		title: "Taghipour, S., Akbari Torkestani, J., & Nazari, S. (2021).",
		desc: "A Novel Clustering Algorithm Based upon Learning Automata for Collaborative Filtering. International Journal of Smart Electrical Engineering, 10(04), 235-243.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:eQOLeE2rZwMC",
		github: "https://civilica.com",
	},
	{
		id: 9,
		category: "Journal Papers",
		image: img,
		title: "Fereydouni, F., Nazari, S., & Osati Eraghi, N. (2022).",
		desc: "An integrated model based machine learning to predict stock market data. International Journal of Smart Electrical Engineering.",
		demo: "https://scholar.google.com/citations?user=NUIXkmIAAAAJ&hl",
		github: "https://civilica.com",
	},
	{
		id: 10,
		category: "Journal Papers",
		image: img,
		title: "Chahardoli, M., Eraghi, N. O., & Nazari, S. (2022).",
		desc: "Namib beetle optimization algorithm: a new meta‐heuristic method for feature selection and dimension reduction. Concurrency and Computation: Practice and Experience, 34(1), e6524.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:YsMSGLbcyi4C",
		github: "https://civilica.com",
	},
	{
		id: 11,
		category: "Journal Papers",
		image: img,
		title: "Taghipour, S., Akbari Torkestani, J., & Nazari, S. (2024).",
		desc: "A Learning Automata-Based Approach to Improve the Scalability of Clustering-Based Recommender Systems. Cybernetics and Systems, 1-32.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:_FxGoFyzp5QC",
		github: "https://civilica.com",
	},
	{
		id: 12,
		category: "Journal Papers",
		image: img,
		title: "Kooshari, A., Fartash, M., Mihannezhad, P., Chahardoli, M., AkbariTorkestani, J., & Nazari, S. (2023).",
		desc: "An optimization method in wireless sensor network routing and IoT with water strider algorithm and ant colony optimization algorithm. Evolutionary Intelligence, 1-19.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:LkGwnXOMwfcC",
		github: "https://civilica.com",
	},
	{
		id: 13,
		category: "Journal Papers",
		image: img,
		title: "S Arab Najafabadi, S Nazari, N Osati Eraghi(2024).",
		desc: "Kinship Recognition based on Deep Scattering   Wavelet Convolutional Neural Network on Wild Facial Image” ,Majlesi Journal of Electrical Engineering 18 (1), 9-19.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:Se3iqnhoufwC",
		github: "https://civilica.com",
	},
	{
		id: 14,
		category: "Conference Papers",
		image: img,
		title: "Nazari, S., Meybodi, M. R., Salehigh, M. A., & Taghipour, S. (2008, November).",
		desc: "An advanced algorithm for finding shortest path in car navigation system. In 2008 First International Conference on Intelligent Networks and Intelligent Systems (pp. 671-674). IEEE.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:9yKSN-GCB0IC",
		github: "https://civilica.com",
	},
	{
		id: 15,
		category: "Conference Papers",
		image: img,
		title: "Nazari, S., & Moin, M. S. (2013, May).",
		desc: "Face recognition using global and local Gabor features. In 2013 21st Iranian Conference on Electrical Engineering (ICEE) (pp. 1-4). IEEE.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:UeHWp8X0CEIC",
		github: "https://civilica.com",
	},
	{
		id: 16,
		category: "Conference Papers",
		image: img,
		title: "Nazari, S., Moin, M. S., & Kanan, H. R. (2014, September).",
		desc: "Cancelable face using chaos permutation. In 7'th International Symposium on Telecommunications (IST'2014) (pp. 925-928). IEEE.",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:d1gkVwhDpl0C",
		github: "https://civilica.com",
	},
	{
		id: 17,
		category: "Journal Papers",
		image: img,
		title: "Fereshteh Aghabeigi, Sara Nazari, Nafiseh Osati Eraghi. (2024, July)",
		desc: "An efficient facial emotion recognition using convolutional neural network with local sorting binary pattern and whale optimization algorithm",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:KlAtU1dfN6UC",
		github: "https://civilica.com",
	},
	{
		id: 18,
		category: "Journal Papers",
		image: img,
		title: "Nafiseh Osati Eraghi Fereshteh Aghabeigi, Sara Nazari. (2023, October)",
		desc: "An optimized facial emotion recognition architecture based on a deep convolutional neural network and genetic algorithm",
		demo: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=NUIXkmIAAAAJ&sortby=pubdate&citation_for_view=NUIXkmIAAAAJ:8k81kl-MbHgC",
		github: "https://civilica.com",
	},
];

export default data;
